// css
import './globals.css'
// bootstrap css
import 'bootstrap/dist/css/bootstrap.min.css';
// my components
import Header from "./components/header/Header"
import Footer from "./components/footer/Footer"
// react
import Script from "next/script";

// meta data
export const metadata = {
  title: 'Business Consulting Company',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* bootstrap popper js */}
      <Script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous" />
      {/* bootstrap js */}
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous" />
      <body>
        {/* header component */}
        <Header />
        {/* all pages */}
        {children}
        {/* footer component */}
        <Footer />
      </body>
    </html>
  )
}
